// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppvqzzphidataxwccvii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdnF6enBoaWRhdGF4d2NjdmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTg2OTIsImV4cCI6MjA3MTg3NDY5Mn0.y4znG6ZWteslz93Vc8TCPjiy6ZrNeuZIQwx9-AGSQ3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});